import { Handler, HandlerEvent, HandlerContext } from '@netlify/functions';
import { supabase } from '../../services/supabaseClient'; // Adjusted path

const commonHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Content-Type': 'application/json',
};

const handler: Handler = async (event: HandlerEvent, context: HandlerContext) => {
  // Handle OPTIONS preflight request for CORS
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 204,
      headers: commonHeaders,
      body: '',
    };
  }

  const pathParts = event.path.split('/').filter(Boolean);
  const resourceId = pathParts.length > 2 ? pathParts[2] : null; //  e.g. /api/products/PRODUCT_ID -> PRODUCT_ID

  try {
    switch (event.httpMethod) {
      case 'GET':
        if (resourceId) {
          // Get single product by ID
          const { data, error } = await supabase
            .from('products')
            .select('*')
            .eq('id', resourceId)
            .single();
          if (error) throw error;
          return { statusCode: 200, headers: commonHeaders, body: JSON.stringify(data) };
        } else {
          // Get all products
          const { data, error } = await supabase.from('products').select('*').order('created_at', { ascending: false });
          if (error) throw error;
          return { statusCode: 200, headers: commonHeaders, body: JSON.stringify(data) };
        }

      case 'POST':
        const newProduct = JSON.parse(event.body || '{}');
        // ID is generated by DB
        const { data: createdData, error: createError } = await supabase
          .from('products')
          .insert(newProduct)
          .select()
          .single();
        if (createError) throw createError;
        return { statusCode: 201, headers: commonHeaders, body: JSON.stringify(createdData) };

      case 'PUT':
        if (!resourceId) return { statusCode: 400, headers: commonHeaders, body: JSON.stringify({ message: 'Product ID required for update' }) };
        const updatedProductData = JSON.parse(event.body || '{}');
        // Don't allow changing ID
        delete updatedProductData.id;
        const { data: updatedData, error: updateError } = await supabase
          .from('products')
          .update(updatedProductData)
          .eq('id', resourceId)
          .select()
          .single();
        if (updateError) throw updateError;
        return { statusCode: 200, headers: commonHeaders, body: JSON.stringify(updatedData) };

      case 'DELETE':
        if (!resourceId) return { statusCode: 400, headers: commonHeaders, body: JSON.stringify({ message: 'Product ID required for delete' }) };
        const { error: deleteError } = await supabase
          .from('products')
          .delete()
          .eq('id', resourceId);
        if (deleteError) throw deleteError;
        return { statusCode: 204, headers: commonHeaders, body: '' }; // No content

      default:
        return { statusCode: 405, headers: commonHeaders, body: JSON.stringify({ message: 'Method Not Allowed' }) };
    }
  } catch (error: any) {
    console.error('Supabase error:', error);
    return {
      statusCode: error.code && typeof error.code === 'string' && error.code.startsWith('PGRST') ? 400 : 500, // Basic Supabase error code check
      headers: commonHeaders,
      body: JSON.stringify({ message: error.message, details: error.details, hint: error.hint }),
    };
  }
};

export { handler };
