// This file will be auto-generated by Supabase CLI.
// Run: npx supabase gen types typescript --linked > types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      admins: {
        Row: {
          email: string
          created_at: string
          added_by: string | null
        }
        Insert: {
          email: string
          created_at?: string
          added_by?: string | null
        }
        Update: {
          email?: string
          created_at?: string
          added_by?: string | null
        }
        Relationships: []
      }
      // START: Product Group Tables (18 tables)
      products_bdr: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_la: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_ag: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_ab_cyr: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_ar_cyr: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_bez_sokr: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_af: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_ds: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_m8: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_jda: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_faith: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_ab_lat: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_gf: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_es: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_gp: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_sd: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_ata: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      products_w: {
        Row: { id: string; name: string; price: number; salon_price: number | null; exchange_rate: number | null; quanity: number | null; created_at: string | null; };
        Insert: { id?: string; name: string; price: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Update: { id?: string; name?: string; price?: number; salon_price?: number | null; exchange_rate?: number | null; quanity?: number | null; created_at?: string | null; };
        Relationships: [];
      };
      // END: Product Group Tables

      customers: {
        Row: {
          id: string
          name: string
          email: string
          phone: string | null
          address_street: string | null
          address_city: string | null
          address_state: string | null
          address_zip: string | null
          address_country: string | null
          join_date: string 
          instagram_handle: string | null
          viber_number: string | null
          created_at: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          name: string
          email: string
          phone?: string | null
          address_street?: string | null
          address_city?: string | null
          address_state?: string | null
          address_zip?: string | null
          address_country?: string | null
          join_date: string
          instagram_handle?: string | null
          viber_number?: string | null
          created_at?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          name?: string
          email?: string
          phone?: string | null
          address_street?: string | null
          address_city?: string | null
          address_state?: string | null
          address_zip?: string | null
          address_country?: string | null
          join_date?: string
          instagram_handle?: string | null
          viber_number?: string | null
          created_at?: string | null
          notes?: string | null
        }
        Relationships: []
      }
      orders: {
        Row: {
          id: string
          customer_id: string
          date: string
          status: "Ordered" | "Shipped" | "Received" | "Calculation" | "AwaitingApproval" | "PaidByClient" | "WrittenOff" | "ReadyForPickup"
          total_amount: number
          notes: string | null
          created_at: string | null
          managed_by_user_email: string | null
        }
        Insert: {
          id?: string
          customer_id: string
          date: string
          status: "Ordered" | "Shipped" | "Received" | "Calculation" | "AwaitingApproval" | "PaidByClient" | "WrittenOff" | "ReadyForPickup"
          total_amount: number
          notes?: string | null
          created_at?: string | null
          managed_by_user_email?: string | null
        }
        Update: {
          id?: string
          customer_id?: string
          date?: string
          status?: "Ordered" | "Shipped" | "Received" | "Calculation" | "AwaitingApproval" | "PaidByClient" | "WrittenOff" | "ReadyForPickup"
          total_amount?: number
          notes?: string | null
          created_at?: string | null
          managed_by_user_email?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            referencedRelation: "customers"
            referencedColumns: ["id"]
          }
        ]
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string | null // Can be null if product was deleted but order item remains
          product_name: string
          quantity: number
          price: number
          discount: number | null
          created_at: string | null
          salon_price_usd: number | null
          exchange_rate: number | null
        }
        Insert: {
          id?: string
          order_id: string
          product_id?: string | null
          product_name: string
          quantity: number
          price: number
          discount?: number | null
          created_at?: string | null
          salon_price_usd?: number | null
          exchange_rate?: number | null
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string | null
          product_name?: string
          quantity?: number
          price?: number
          discount?: number | null
          created_at?: string | null
          salon_price_usd?: number | null
          exchange_rate?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            referencedRelation: "orders"
            referencedColumns: ["id"]
          }
        ]
      }
      managed_users: {
        Row: {
          id: string 
          name: string
          email: string
          notes: string | null
          created_at: string 
          added_by_admin_email: string | null
        }
        Insert: {
          id?: string 
          name: string
          email: string
          notes?: string | null
          created_at?: string 
          added_by_admin_email?: string | null
        }
        Update: {
          id?: string
          name?: string
          email?: string
          notes?: string | null
          created_at?: string
          added_by_admin_email?: string | null
        }
        Relationships: [] 
      }
      expenses: {
        Row: {
          id: string
          name: string
          amount: number
          date: string
          notes: string | null
          created_at: string
          created_by_user_email: string | null
        }
        Insert: {
          id?: string
          name: string
          amount: number
          date: string
          notes?: string | null
          created_at?: string
          created_by_user_email?: string | null
        }
        Update: {
          id?: string
          name?: string
          amount?: number
          date?: string
          notes?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          user_email: string
          message: string
          link: string | null
          type: 'NEW_ORDER' | 'STATUS_UPDATE' | 'LOW_STOCK' | 'GENERAL'
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_email: string
          message: string
          link?: string | null
          type: 'NEW_ORDER' | 'STATUS_UPDATE' | 'LOW_STOCK' | 'GENERAL'
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_email?: string
          message?: string
          link?: string | null
          type?: 'NEW_ORDER' | 'STATUS_UPDATE' | 'LOW_STOCK' | 'GENERAL'
          is_read?: boolean
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}