import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types/supabase'; // Will be generated by Supabase CLI

// Ensure these environment variables are set in your Netlify project settings
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Supabase URL and Anon Key must be defined in environment variables.');
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

// Note: To generate the Database type definition (../types/supabase.ts):
// 1. Install Supabase CLI: npm install supabase --save-dev
// 2. Log in: npx supabase login
// 3. Link your project: npx supabase link --project-ref YOUR_PROJECT_ID
// 4. Generate types: npx supabase gen types typescript --linked > types/supabase.ts
// Replace YOUR_PROJECT_ID with your actual Supabase project ID.
// For now, we'll use Supabase client with 'any' for table/column types if 'Database' is not yet generated.
// To use with 'any' before type generation:
// export const supabase = createClient(supabaseUrl, supabaseAnonKey);
